#!/bin/bash

set -ex

BDF_ESC=$(echo "0000:05:00:0" | sed -r 's/\:/*/g')

chmod a+rwX /sys/bus/pci/devices/$BDF_ESC/vendor
chmod a+rwX /sys/bus/pci/devices/$BDF_ESC/device
chmod a+rwX /sys/bus/pci/devices/$BDF_ESC/xdma/*_h2c_0
