#!/usr/bin/env bash
# List the chipyard files to sync to the compile host.
#
# usage: make-manifest.sh [OUT]   (default OUT: manifest.txt next to this script)
#
# The set is what git sees, in chipyard and every submodule: tracked files plus
# untracked files that aren't gitignored. Build outputs, run results and .git
# dirs are excluded because they're ignored or not files in the index. On top
# of that:
#   EXTRA    gitignored files the build still needs
#   EXCLUDE  path prefixes dropped even if git lists them
# Paths are relative to the chipyard root, one per line (rsync --files-from).
# Prints a size summary per directory to stderr for review.

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
CY_DIR=$(cd "$SCRIPT_DIR/../../.." && pwd)
OUT=${1:-$SCRIPT_DIR/manifest.txt}

EXTRA=(
    env.sh                  # generated by build-setup.sh
    sims/firesim/env.sh     # sourced by sourceme-manager.sh
    # made by firesim_target_symlink_hook; firesim-main.jar must be built with
    # them present, and make won't rebuild it if they appear later (old mtimes)
    sims/firesim/sim/midas/src/main/scala/target-symlinks/bridgeinterfaces/src
    sims/firesim/sim/midas/src/main/scala/target-symlinks/goldengateimplementations/src
)
EXCLUDE=(
    software/firemarshal/   # workload images, not used by RTL/metasim builds
    sims/firesim/deploy/results-build/
    sims/firesim/deploy/results-workload/
    sims/firesim/remote-build/manifest.txt
    sims/firesim/remote-build/tmp/
)

cd "$CY_DIR"

list_repo() {  # $1 = repo path relative to CY_DIR ("" for root)
    git -C "${1:-.}" ls-files -z --cached --others --exclude-standard |
        while IFS= read -r -d '' f; do printf '%s\n' "${1:+$1/}$f"; done
}

{
    list_repo ""
    # build.sbt treats generators/<name>/.git existing as "submodule
    # initialized", and uses it to pick which optional generators to build, so
    # those .git files (one-line gitdir pointers) are included. Only those: the
    # pointers dangle on the compile host, and sbt-git (pulled in by FireSim's
    # sbt-ghpages) crashes on a dangling .git but is fine with none.
    git submodule foreach --recursive --quiet 'echo "$displaypath"' |
        while read -r sub; do
            list_repo "$sub"
            if [[ $sub =~ ^generators/[^/]+$ ]]; then printf '%s\n' "$sub/.git"; fi
        done
    printf '%s\n' "${EXTRA[@]}"
} |
    # keep regular files and symlinks (including symlinks to dirs, which rsync
    # sends as links); drops submodule gitlinks and nested (non-submodule)
    # repos, which git lists as real directories
    while IFS= read -r f; do
        if [ -L "$f" ] || { [ -f "$f" ] && [ ! -d "$f" ]; }; then printf '%s\n' "$f"; fi
    done |
    awk -v ex="$(printf '%s\n' "${EXCLUDE[@]}")" '
        BEGIN { n = split(ex, p, "\n") }
        { for (i = 1; i <= n; i++) if (p[i] != "" && index($0, p[i]) == 1) next; print }
    ' |
    LC_ALL=C sort -u > "$OUT"

# summary: file count and size per directory, two levels deep
{
    echo "manifest: $OUT"
    printf '%s\n' "$(wc -l < "$OUT") files, $(tr '\n' '\0' < "$OUT" | du -ch --files0-from=- | tail -1 | cut -f1) total"
    echo
    printf '%8s %8s  %s\n' SIZE FILES DIR
    tr '\n' '\0' < "$OUT" | du -b --files0-from=- |
        awk -F'\t' '{
            n = split($2, a, "/"); d = (n > 2) ? a[1] "/" a[2] : (n == 2 ? a[1] : ".")
            s[d] += $1; c[d]++
        } END { for (d in s) printf "%d\t%d\t%s\n", s[d], c[d], d }' |
        sort -rn | head -40 |
        awk -F'\t' '{ printf "%7.1fM %8d  %s\n", $1 / 1048576, $2, $3 }'
} >&2
